### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by ArchVivi** [m-byte918/AgarOSS#10]
![image](https://user-images.githubusercontent.com/24535879/44632995-82f31980-a939-11e8-81db-edb042594f09.png)
this is annoying and it's while compiling

**Comment by BorysDev** [comment]
What command are you using to compile may i know?

**Comment by ArchVivi** [comment]
Well I am using compile.bat

**Comment by BorysDev** [comment]
Give this command a try please:
```BATCH
g++ -std=c++17 -o OgarCpp -I ./*.cpp Connection/*.cpp Entities/*.cpp Game/*.cpp Modules/*.cpp Packets/*.cpp -luWS -lz -lssl -pthread

```

**Comment by m-byte918** [comment]
@ZmanGamer It works fine for me. Have you moved `compile.bat` or the `Game` folder? Try re-downloading and running it in the same folder that it comes in.

**Comment by freaky767** [comment]
getting same error and didnt move anything

**Comment by ArchVivi** [comment]
i have not moved anything

**Comment by ArchVivi** [comment]
i am also on win7 so...

**Comment by m-byte918** [comment]
Use this instead: `g++ -std=c++17 -o OgarCpp -I /*.cpp Connection/*.cpp Entities/*.cpp Game/*.cpp Modules/*.cpp Player/*.cpp Protocol/*.cpp -luWS -lz -lssl -pthread`
I forgot that on windows you don't use `./` to get the current directory, lol

**Comment by m-byte918** [comment]
Fixed in https://github.com/Megabyte918/OgarCpp/commit/2fc0ac282cd7b1b8175b7d85a120f3dc990160fb
