### ISSUE TITLE
error: no match for ‘operator=’

### ISSUE THREAD

**Issue by tariqazmat101** [m-byte918/AgarOSS#17]
Hello, I keep getting the following error: 
![2020-08-02-183917_1453x413_scrot](https://user-images.githubusercontent.com/19142578/89134053-d429c180-d4ef-11ea-8508-841552834dd6.png)
I'm on linux, Ubuntu 18.04 

GCC version is 7.5.0 
Gnu Make is 4.1 
CMAKE is 3.17.3 

Any ideas? 

EDIT: What operating system and version was used to compile the game?

**Comment by kapooky** [comment]
What operating system and version was used to compile the game?

**Comment by tariqazmat101** [comment]
Given that the vast majority of issues are installation based, I suggest that you build a dockerfile of your local dev enviorment, and push that out as an image to a public docker repository. We, the users, can then pull that image, and run it as a container to get a complete replica of your dev envrioment without any fuss. 

Barbosik's multi-ogar did something similar: 
https://github.com/Barbosik/MultiOgar/blob/master/Dockerfile
