### ISSUE TITLE
Why do you pass simple data types by reference? 

### ISSUE THREAD

**Issue by NuclearC** [m-byte918/AgarOSS#6]
For example this part:
```cpp
 static int rand(const int& min, const int& max) {
```
Whats the reason for passing the integers by reference? I dont think it will save even a nanosecond for run-time.

**Comment by m-byte918** [comment]
I read somewhere a while ago that passing types by reference is more efficient than by value, but I learned recently that it is not necessarily true for simple built in data types. I have fixed this in my private version.
