### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by mafiakb** [m-byte918/AgarOSS#7]
How run in node?

**Comment by Luka967** [comment]
This isn't even finished. And you don't.

**Comment by SuperOP535** [comment]
lmao

**Comment by BorysDev** [comment]
```BASH
rm -rf urself
```

**Comment by freaky767** [comment]
this isn't node, its c++

**Comment by mafiakb** [comment]
Then how run in centos?

**Comment by ItzLevvie** [comment]
This is for Windows

**Comment by mafiakb** [comment]
@ItzLevvie how use?

**Comment by BorysDev** [comment]
This is for IBM BASIC

**Comment by freaky767** [comment]
use a commodore 64

**Comment by NuclearC** [comment]
Get the free version of Visual Studio 2017 (Community edition), open the sln file, go to Build -> Build Solution, and find your exe file in the binary directories
